### ISSUE TITLE
Submit PBTA SSM for ICGC Release 28

### ISSUE THREAD

**Issue by yuankunzhu** [d3b-center/bixeng#11]
We need to submit Simple Somatic Mutation data for PBTA to ICGC.

ICGC SSM Submission Guide: https://docs.icgc.org/submission/guide/icgc-simple-somatic-mutation-format/

We need to figure out:
- [ ] what has already been loaded @yuankunzhu 
- [ ] are you going to load CNV/Expression data? @allisonheath 
- [ ] what are those 359 non-molecular donors? @allisonheath 
- [ ] prepare/formatting for newly submission
- [ ] run the validation: https://docs.icgc.org/submission/guide/overview/submission-validation/

-----
Hello Allison,
 
I hope all is well. I’m just following up on our earlier email regarding the status of 359 non-molecular donors in DCC (https://icgc.org/ZEn). You mentioned a while  back you were planning to submit molecular data for these 359 donors. We are currently accepting data submissions for Release 28 (which will be the last Release for ICGC). Do you plan to submit molecular data (ie. SSM) for these donors in this Release?
 
Regards,
Hardeep
 
Hardeep Nahal-Bose
Senior Bioinformatics Data Manager
Data Coordination Centre
International Cancer Genome Consortium

**Comment by yuankunzhu** [comment]
@allisonheath I'm about to work on this ticket now, just to make sure we're on the same page, we are only doing the "Primary CBTTC" data for this release, correct, not the current PBTA which will also includes PNOC and CNMC data.

**Comment by allisonheath** [comment]
That's my understanding - might want to double check that "Primary CBTTC" includes more samples than what's currently on ICGC?

**Comment by yuankunzhu** [comment]
```
submission
├── core-clinical-files
│   ├── donor.txt
│   ├── sample.txt
│   └── specimen.txt
└── experimental-files
    ├── cnsm_m.txt
    ├── cnsm_p.txt
    ├── exp_g.txt
    ├── exp_m.txt
    ├── ssm_m.txt
    └── ssm_p.txt
```

**Comment by yuankunzhu** [comment]
using aliquot ID as sample names. For legacy CBTTC samples, using `SDG_ID-[T/N]` as sample names, for multi aliquoted samples, using underscore instead dot as ICGC accepted [`^[\w+\-\_]+$`](http://www.regexplanet.com/advanced/java/index.html?regex=%5E%5B%5Cw%2B%5C-%5C_%5D%2B%24&input=ov-45&input=90343a&input=BRCAZ-TG)

**Comment by yuankunzhu** [comment]
```
next unless $.>2;
next if /^Unknown/;
next if /^MIR/;
next if /^AC\d+/;
next if /^AL\d+/;
next if /^AP\d+/;
next if /^C\d+orf\d+/;
next if /^ENSR/;
next if /^LINC/;
next if /^SLC/;
next if /^ZNF/;
next if $chr=~/^GL/;
```
