### ISSUE TITLE
missing CBTTC file

### ISSUE THREAD

**Issue by yuankunzhu** [d3b-center/bixeng#25]
from Michele's Slack:
```
Michele Mattioni [8:07 AM]
hey
I've got a question for you
we have Krutika, which I think you know
trying to access a CBBTC file.
this is the file https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-06/files/5b74a2f1e4b0934af82bda49/
but it's not there anymore. It's managed on a volume S3. Do you know why?

yuankun [8:37 AM]
ok, looking into that
looks like it’s from Bo’s volume?
will check with him
```

**Comment by zhangb1** [comment]
@yuankunzhu 

The reason they are missing ,is when I exported to the penn s3 bucket, Komal moved all the files to another folder ,so  all the file links can't be found , you can't download them.

I copied all the CBTTC RNAseq expression results to the project : https://cavatica.sbgenomics.com/u/zhangb1/rsem-results/files/#q

I added Krukika  to the project , she can access the data now.

**Comment by kgaonkar6** [comment]
Thank you for looking into this.
