### ISSUE TITLE
Create SNP status matrix for Matt Hocking's request

### ISSUE THREAD

**Issue by yuankunzhu** [d3b-center/bixeng#34]
cavatica project: https://cavatica.sbgenomics.com/u/cavatica/mwrb-s6h9/files/#q?sort.by=name&sort.order=asc&path=VCFs

**Comment by zhangb1** [comment]
combine 114 vcf into one xlsx.


Gene | CHR | POS | ID | REF | ALT | LEVEL | Count| samples...
-- | -- | -- | -- | -- | -- | -- | -- | --

[matrix.xlsx](https://github.com/d3b-center/bixeng/files/2721999/matrix.xlsx)

**Comment by yuankunzhu** [comment]
sent the results. close this ticket
